/**
 * Zeus CRM Pro v4.0 - Swagger/OpenAPI Documentation
 */

const swaggerSpec = {
  openapi: '3.0.3',
  info: {
    title: 'Zeus CRM Pro API',
    version: '4.0.0',
    description: 'API completa do Zeus CRM Pro — Sistema de CRM para vendas de painéis LED com AI, assinatura digital, campanhas multi-canal e automação de workflows.',
    contact: { name: 'Zeus Tecnologia', email: 'contato@zeus.com' },
    license: { name: 'Proprietário' }
  },
  servers: [
    { url: '/api', description: 'API Principal' }
  ],
  tags: [
    { name: 'Auth', description: 'Autenticação e autorização' },
    { name: 'Leads', description: 'Gestão de leads e pipeline' },
    { name: 'Orçamentos', description: 'Criação e gestão de orçamentos' },
    { name: 'Contratos', description: 'Contratos com assinatura digital ClickSign' },
    { name: 'Produtos', description: 'Catálogo de produtos' },
    { name: 'Tasks', description: 'Gestão de tarefas' },
    { name: 'Marketing', description: 'Campanhas, funis, anúncios e reviews' },
    { name: 'AI', description: 'Inteligência artificial (GPT-4o-mini)' },
    { name: 'Exports', description: 'Exportação PDF/Excel' },
    { name: 'Import', description: 'Importação de leads CSV/Excel' },
    { name: 'Deduplication', description: 'Deduplicação de leads' },
    { name: 'Workflows', description: 'Automação de workflows' },
    { name: 'Chatbot', description: 'Chatbot AI para atendimento' },
    { name: 'Landing Pages', description: 'Builder de landing pages' },
    { name: 'A/B Tests', description: 'Testes A/B para campanhas' },
    { name: 'Custom Reports', description: 'Relatórios customizáveis' },
    { name: 'Scheduled Reports', description: 'Relatórios agendados' },
    { name: 'Permissions', description: 'Permissões granulares (RBAC)' },
    { name: 'Integrations', description: 'Marketplace de integrações' },
    { name: 'NPS', description: 'Net Promoter Score' },
    { name: 'Users', description: 'Gestão de usuários' },
    { name: 'Settings', description: 'Configurações do sistema' }
  C, { name: 'Auth', description: 'Autenticação e autorização' },
    { name: 'Leads', description: 'Gestão de leads e pipeline' },
    { name: 'Orçamentos', description: 'Criação e gestão de orçamentos' },
    { name: 'Contratos', description: 'Contratos com assinatura digital ClickSign' },
    { name: 'Produtos', description: 'Catálogo de produtos' },
    { name: 'Tasks', description: 'Gestão de tarefas' },
    { name: 'Marketing', description: 'Campanhas, funis, anúncios e reviews' },
    { name: 'AI', description: 'Inteligência artificial (GPT-4o-mini)' },
    { name: 'Exports', description: 'Exportação PDF/Excel' },
    { name: 'Import', description: 'Importação de leads CSV/Excel' },
    { name: 'Deduplication', description: 'Deduplicação de leads' },
    { name: 'Workflows', description: 'Automação de workflows' },
    { name: 'Chatbot', description: 'Chatbot AI para atendimento' },
    { name: 'Landing Pages', description: 'Builder de landing pages' },
    { name: 'A/B Tests', description: 'Testes A/B para campanhas' },
    { name: 'Custom Reports', description: 'Relatórios customizáveis' },
    { name: 'Scheduled Reports', description: 'Relatórios agendados' },
    { name: 'Permissions', description: 'Permissões granulares (RBAC)' },
    { name: 'Integrations', description: 'Marketplace de integrações' },
    { name: 'NPS', description: 'Net Promoter Score' },
    { name: 'Users', description: 'Gestão de usuários' },
    { name: 'Settings', description: 'Configurações do sistema' }
  C, { name: 'Auth', description: 'Autenticação e autorização' },
    { name: 'Leads', description: 'Gestão de leads e pipeline' },
    { name: 'Orçamentos', description: 'Criação e gestão de orçamentos' },
    { name: 'Contratos', description: 'Contratos com assinatura digital ClickSign' },
    { name: 'Produtos', description: 'Catálogo de produtos' },
    { name: 'Tasks', description: 'Gestão de tarefas' },
    { name: 'Marketing', description: 'Campanhas, funis, anúncios e reviews' },
    { name: 'AI', description: 'Inteligência artificial (GPT-4o-mini)' },
    { name: 'Exports', description: 'Exportação PDF/Excel' },
    { name: 'Import', description: 'Importação de leads CSV/Excel' },
    { name: 'Deduplication', description: 'Deduplicação de leads' },
    { name: 'Workflows', description: 'Automação de workflows' },
    { name: 'Chatbot', description: 'Chatbot AI para atendimento' },
    { name: 'Landing Pages', description: 'Builder de landing pages' },
    { name: 'A/B Tests', description: 'Testes A/B para campanhas' },
    { name: 'Custom Reports', description: 'Relatórios customizáveis' },
    { name: 'Scheduled Reports', description: 'Relatórios agendados' },
    { name: 'Permissions', description: 'Permissões granulares (RBAC)' },
    { name: 'Integrations', description: 'Marketplace de integrações' },
    { name: 'NPS', description: 'Net Promoter Score' },
    { name: 'Users', description: 'Gestão de usuários' },
    { name: 'Settings', description: 'Configurações do sistema' }
  C, tags: [
    { name: 'Auth', description: 'Autenticação e autorização' },
    { name: 'Leads', description: 'Gestão de leads e pipeline' },
    { name: 'Orçamentos', description: 'Criação e gestão de orçamentos' },
    { name: 'Contratos', description: 'Contratos com assinatura digital ClickSign' },
    { name: 'Produtos', description: 'Catálogo de produtos' },
    { name: 'Tasks', description: 'Gestão de tarefas' },
    { name: 'Marketing', description: 'Campanhas, funis, anúncios e reviews' },
    { name: 'AI', description: 'Inteligência artificial (GPT-4o-mini)' },
    { name: 'Exports', description: 'Exportação PDF/Excel' },
    { name: 'Import', description: 'Importação de leads CSV/Excel' },
    { name: 'Deduplication', description: 'Deduplicação de leads' },
    { name: 'Workflows', description: 'Automação de workflows' },
    { name: 'Chatbot', description: 'Chatbot AI para atendimento' },
    { name: 'Landing Pages', description: 'Builder de landing pages' },
    { name: 'A/B Tests', description: 'Testes A/B para campanhas' },
    { name: 'Custom Reports', description: 'Relatórios customizáveis' },
    { name: 'Scheduled Reports', description: 'Relatórios agendados' },
    { name: 'Permissions', description: 'Permispões granulares (RBAC)' },
    { name: 'Integrations', description: 'Marketplace de integrações' },
    { name: 'NPS', description: 'Net Promoter Score' },
    { name: 'Users', description: 'Gestão de usuários' },
    { name: 'Settings', description: 'Configurações do sistema' }
  }]
};